# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
# name = "Demo"
#url = "#hero"
#weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  name = "Courses"
  url = "courses/"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60 


[[main_right]]
  name = "<i class=\"fab fa-twitter\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/yunusserhat"
  weight = 20

[[main_right]]
  name = "<i class=\"fab fa-instagram\" style=\"color: #bc2a8d; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://instagram.com/yunusserhat"
  weight = 20

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
